"use client";

import { useEffect, useState } from "react";
import { auth } from "@/lib/firebase";
import { onAuthStateChanged } from "firebase/auth";
import { useRouter } from "next/navigation";
import Link from "next/link";

type Recommendation = {
  id: string;
  type: "optimization" | "efficiency" | "infrastructure" | "info" | "success";
  title: string;
  description: string;
  impact: {
    energySavedWh: number;
    co2SavedGrams: number;
    costReductionPct: number;
  };
  actionText: string;
  actionLink: string;
};

export default function RecommendationsPage() {
  const router = useRouter();
  const [orgId, setOrgId] = useState<string | null>(null);
  const [recs, setRecs] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (user) => {
      if (user) {
        setOrgId(user.uid);
        fetchRecommendations(user.uid);
      } else {
        router.push("/login");
      }
    });
    return () => unsub();
  }, [router]);

  async function fetchRecommendations(uid: string) {
    try {
      const res = await fetch(`/api/recommendations?orgId=${uid}`);
      if (res.ok) {
        const data = await res.json();
        setRecs(data.recommendations || []);
      }
    } catch (e) {
      console.error("Failed to fetch recs", e);
    } finally {
      setLoading(false);
    }
  }

  const getTypeStyles = (type: string) => {
    switch (type) {
      case "optimization": return { bg: "bg-purple-500/10", border: "border-purple-500/20", icon: "text-purple-400" };
      case "efficiency": return { bg: "bg-blue-500/10", border: "border-blue-500/20", icon: "text-blue-400" };
      case "infrastructure": return { bg: "bg-orange-500/10", border: "border-orange-500/20", icon: "text-orange-400" };
      case "success": return { bg: "bg-[#10b981]/10", border: "border-[#10b981]/20", icon: "text-[#10b981]" };
      default: return { bg: "bg-zinc-500/10", border: "border-zinc-500/20", icon: "text-zinc-400" };
    }
  };

  const getIcon = (type: string) => {
    switch (type) {
      case "optimization": return <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>;
      case "efficiency": return <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>;
      case "infrastructure": return <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>;
      case "success": return <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="M22 4L12 14.01l-3-3"/></svg>;
      default: return <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>;
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#050505]">
         <div className="w-10 h-10 border-2 border-[#10b981]/20 border-t-[#10b981] rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="px-6 py-8 sm:px-10 lg:px-14 selection:bg-[#10b981]/30">
      <div className="mx-auto w-full max-w-7xl space-y-10 pb-20">
        <header className="flex flex-col gap-1.5 border-b border-white/5 pb-8">
          <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-[#10b981] font-bold">
            <div className="w-1.5 h-1.5 rounded-full bg-[#10b981] shadow-[0_0_8px_#10b981]" />
            AI Diagnostics
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl text-white">
            Optimization Engine
          </h1>
          <p className="mt-3 text-sm text-zinc-500 max-w-2xl leading-relaxed font-normal">
            Data-driven sustainability insights generated by analyzing your recent inference telemetry. 
            Implement these architectural shifts to reduce grid impact and compute overhead.
          </p>
        </header>

        <section className="space-y-6">
          {recs.map((rec) => {
            const styles = getTypeStyles(rec.type);
            return (
              <article key={rec.id} className="relative overflow-hidden rounded-[32px] border border-white/5 bg-[#0a0a0a]/60 backdrop-blur-xl p-8 hover:border-white/10 transition-colors group">
                <div className="flex flex-col lg:flex-row gap-8 lg:items-center justify-between relative z-10">
                  
                  {/* Left Side: Info */}
                  <div className="flex gap-6 max-w-3xl">
                    <div className={`w-14 h-14 rounded-2xl ${styles.bg} border ${styles.border} flex items-center justify-center shrink-0`}>
                      <div className={styles.icon}>{getIcon(rec.type)}</div>
                    </div>
                    <div className="space-y-3">
                      <div className="flex items-center gap-3">
                        <h2 className="text-xl font-bold text-white tracking-tight">{rec.title}</h2>
                        <span className={`px-2.5 py-1 rounded-lg text-[9px] font-bold uppercase tracking-widest ${styles.bg} ${styles.icon} border ${styles.border}`}>
                          {rec.type}
                        </span>
                      </div>
                      <p className="text-sm text-zinc-400 leading-relaxed font-medium">
                        {rec.description}
                      </p>
                    </div>
                  </div>

                  {/* Right Side: Impact & Action */}
                  <div className="flex flex-col sm:flex-row lg:flex-col gap-6 lg:items-end justify-between items-center bg-[#050505] lg:bg-transparent p-6 lg:p-0 rounded-2xl border border-white/5 lg:border-none">
                    
                    <div className="flex items-center gap-6 lg:justify-end">
                      {rec.impact.energySavedWh > 0 && (
                        <div className="text-center">
                          <p className="text-2xl font-bold text-sky-400 tabular-nums">-{rec.impact.energySavedWh} <span className="text-sm text-sky-400/50">Wh</span></p>
                          <p className="text-[9px] uppercase font-bold tracking-widest text-zinc-600 mt-1">Energy Saving</p>
                        </div>
                      )}
                      {rec.impact.co2SavedGrams > 0 && (
                        <div className="text-center pr-6 border-r border-white/10 lg:pr-0 lg:border-none">
                          <p className="text-2xl font-bold text-orange-400 tabular-nums">-{rec.impact.co2SavedGrams} <span className="text-sm text-orange-400/50">g</span></p>
                          <p className="text-[9px] uppercase font-bold tracking-widest text-zinc-600 mt-1">CO₂ Reduction</p>
                        </div>
                      )}
                      {rec.impact.costReductionPct > 0 && (
                        <div className="text-center pl-6 border-l border-white/10">
                          <p className="text-2xl font-bold text-[#10b981] tabular-nums">-{rec.impact.costReductionPct}%</p>
                          <p className="text-[9px] uppercase font-bold tracking-widest text-zinc-600 mt-1">Cost Impact</p>
                        </div>
                      )}
                    </div>

                    <Link 
                      href={rec.actionLink}
                      className={`inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl text-xs font-bold uppercase tracking-widest transition-all ${
                        rec.type === 'success' || rec.type === 'info' 
                          ? 'bg-white/5 text-zinc-400 hover:bg-white/10 hover:text-white'
                          : 'bg-[#10b981] text-black hover:bg-[#34d399] shadow-[0_0_20px_rgba(16,185,129,0.2)]'
                      }`}
                    >
                      {rec.actionText}
                      <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M5 12h14M12 5l7 7-7 7"/></svg>
                    </Link>
                  </div>
                </div>

                {/* Subtle Background Accent based on type */}
                <div className={`absolute -inset-24 opacity-[0.02] mix-blend-screen pointer-events-none group-hover:opacity-[0.04] transition-opacity ${styles.bg}`} />
              </article>
            );
          })}
        </section>
      </div>
    </div>
  );
}
